<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rate_limiter.proto

namespace Limiter;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>limiter.AcquireRequest</code>
 */
class AcquireRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string alias = 1;</code>
     */
    private $alias = '';
    /**
     * Generated from protobuf field <code>int32 timeout = 2;</code>
     */
    private $timeout = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $alias
     *     @type int $timeout
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RateLimiter::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string alias = 1;</code>
     * @return string
     */
    public function getAlias()
    {
        return $this->alias;
    }

    /**
     * Generated from protobuf field <code>string alias = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAlias($var)
    {
        GPBUtil::checkString($var, True);
        $this->alias = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 timeout = 2;</code>
     * @return int
     */
    public function getTimeout()
    {
        return $this->timeout;
    }

    /**
     * Generated from protobuf field <code>int32 timeout = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTimeout($var)
    {
        GPBUtil::checkInt32($var);
        $this->timeout = $var;

        return $this;
    }

}

