<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rate_limiter.proto

namespace Limiter;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>limiter.GetRateReply</code>
 */
class GetRateReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool ret = 1;</code>
     */
    private $ret = false;
    /**
     * Generated from protobuf field <code>int32 permits = 2;</code>
     */
    private $permits = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $ret
     *     @type int $permits
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RateLimiter::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool ret = 1;</code>
     * @return bool
     */
    public function getRet()
    {
        return $this->ret;
    }

    /**
     * Generated from protobuf field <code>bool ret = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setRet($var)
    {
        GPBUtil::checkBool($var);
        $this->ret = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 permits = 2;</code>
     * @return int
     */
    public function getPermits()
    {
        return $this->permits;
    }

    /**
     * Generated from protobuf field <code>int32 permits = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPermits($var)
    {
        GPBUtil::checkInt32($var);
        $this->permits = $var;

        return $this;
    }

}

